name: Inner Link Coaching
favicon: null
layout_spectrum: 0.2346587956417352
typography_spectrum: 0.9673266613390297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7661572790239006
  lightness: 0.8388096571434289
  saturation: 0.885710576782003
  rhythmicContrast: 0.3370616128668189
purpose: []
