name: Inner Link Coaching
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00c8fc'
    - '#5ee083'
    - '#337745'
    - '#4da958'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
